run:
	chmod 777 1exp
	chmod 777 2exp
	chmod 777 3exp
	chmod 777 1exp/py1exp.py
	chmod 777 1exp/tcl1exp.tcl
	chmod 777 2exp/py2exp.py
	chmod 777 2exp/tcl2exp.tcl
	chmod 777 3exp/py3exp.py
	chmod 777 3exp/tcl3exp.tcl

