#! /usr/bin/python
import requests
from sets import Set
from Queue import Queue

url = 'http://cs5700f16.ccs.neu.edu/accounts/login/?next=/fakebook/'
client = requests.session()
client.get(url)
csrftoken = client.cookies['csrftoken']

payload = {
	'username': '001723441',
	'password': '3WZ251B0',
	'csrfmiddlewaretoken': csrftoken,
	'next': '/fakebook/'
}

response = client.post(url, data=payload)
response1 = client.get('http://cs5700f16.ccs.neu.edu/fakebook/596548185/')
print(response1.text)
# print(response.text)

print "\nend\n"


