#!/usr/bin/env bash

# get arguments
while getopts "p:o:n:u:i:" opt; do
	case $opt in
	p)
		port=$OPTARG
		;;
	o)
		origin=$OPTARG
		;;
	n)
		name=$OPTARG
		;;
	u)
		user=$OPTARG
		;;
	i)
		key=$OPTARG
		;;
	?)
		echo "Invalid Usage"
		exit 1
		;;
	esac
done

# replica server ips
servers=("54.210.1.206" "54.67.25.76" "35.161.203.105" "52.213.13.179" "52.196.161.198" "54.255.148.115" "13.54.30.86" "52.67.177.90" "35.156.54.135")

# copy httpserver code to replica servers and provide execute permissions
for server in "${servers[@]}"
do
	scp -i $key -o StrictHostKeyChecking=no -r nr_http $user@$server:~
	ssh -i $key -o StrictHostKeyChecking=no $user@$server "cd nr_http && chmod +x httpserver"
done

# copy dnsserver code to ccs server and provide execute permission
scp -i $key -r nr_dns $user@cs5700cdnproject.ccs.neu.edu:~
ssh -i $key $user@cs5700cdnproject.ccs.neu.edu "cd nr_dns && chmod +x dnsserver"


