#!/bin/bash

# get arguments
while getopts "p:o:n:u:i:" opt; do
	case $opt in
	p)
		port=$OPTARG
		;;
	o)
		origin=$OPTARG
		;;
	n)
		name=$OPTARG
		;;
	u)
		user=$OPTARG
		;;
	i)
		key=$OPTARG
		;;
	?)
		echo "Invalid Usage"
		exit 1
		;;
	esac
done

# replica server
servers=("54.210.1.206"
"54.67.25.76"
"35.161.203.105" 
"52.213.13.179" 
"52.196.161.198"
"54.255.148.115"
"13.54.30.86"
"52.67.177.90"
"35.156.54.135")

# ssh into replica server, kill httpserver and remove files
for server in "${servers[@]}"
do
	ssh -i $key -o StrictHostKeyChecking=no $user@$server "pkill httpserver -u $user"
	ssh -i $key -o StrictHostKeyChecking=no $user@$server "rm -rf nr_http"
done

# ssh into ccs server, kill dnsserver and remove files
ssh -i $key $user@cs5700cdnproject.ccs.neu.edu "pkill dnsserver -u $user"
ssh -i $key $user@cs5700cdnproject.ccs.neu.edu "rm -rf nr_dns"


